name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 2"

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest cloudflared version
        id: cloudflared_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | grep '"tag_name":' | cut -d '"' -f 4)
          echo "Latest cloudflared version is ${LATEST_VERSION}"
          echo "CLOUDFLARED_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
        
      - name: Set ENV
        run: echo "TAG=$(echo $(date +%Y.%m.%d))" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            CLOUDFLARED_VERSION=${{ env.CLOUDFLARED_VERSION }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            homeall/cloudflared:latest
            
      - name: Create github release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.TAG }}
          allowUpdates: true
          makeLatest: true
