name: trivy-ghcr-scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 9 * * 2'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  IMAGE_REF: ghcr.io/${{ github.repository }}:latest

jobs:
  scan-ghcr-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the latest image from GHCR
        run: |
          docker pull ${{ env.IMAGE_REF }}

      - name: Run Trivy vulnerability scanner (table)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: '${{ env.IMAGE_REF }}'
          format: 'table'
          exit-code: 1 
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: '${{ env.IMAGE_REF }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Save Trivy table output to file
        run: |
          trivy image --format table \
            --ignore-unfixed \
            --severity CRITICAL,HIGH \
            ${{ env.IMAGE_REF }} > trivy-results.txt

      - name: Upload Trivy table report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-table-report
          path: trivy-results.txt
